# Generated by Django 5.0.1 on 2024-01-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userName',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='Maicol Rojas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='maidanlrojas', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
